ynode = Xynode or {}
local Xynode = Xynode


Xynode.sets = {

[1] =
	{
		zoneid = 283,
		name = "Fungal Grotto I",
		link = "https://www.xynodegaming.com/fungal-grotto-1",
		sets = {838,919,886,1103},
		bosses =
		{
			[1] =
				{
					name = "TAZKAD THE PACKMASTER",
					mechanic = "|t24:24:xynode/icons/xynode_boss_over.dds|t|cffff00 TAZKAD THE PACKMASTER |r|t24:24:xynode/icons/xynode_boss_over.dds|t\n\nThis boss has a little army with him, they are not too tough but you are going to need to get your tank to first of all grab the boss and then pull the additional enemies as close to him as possible. The 2 archers can be interrupted if they attempt to fire off their acid spray type ability and the 3 Durzogs can usually be dispatched quickly with aoe damage. Don't run away if you get agro, simply block and let the tank get the dogs off you and then focus the boss afterwards. The trash he has with him are relatively low health so although they can cause a problem to start with, they wont be there for long.\n\n|cffff00Blood Craze|r - A pretty basic physical damage attack which to a healthy tank will do minimal damage, this attack shouldn't cause much of a problem at all but if you are a dps, so long as you have a shield available or a small heal from the healer this won't be much of an issue. A very small amount of damage but be sure to note when you have it so you can get a heal if need be.\n\n|cffff00Agony|r - Very much like the Nightblade ability, this will be cast on the person with agro(usually the tank). This does a small amount of damage over time and initially stuns. So if you are caught you will have to break free, HOWEVER this ability has a cast time and CAN be interrupted. Keep your eyes peeled for this effect.\n\n\n"
				},
			[2] =
				{
					name = "WAR CHIEF OZOZAI",
					mechanic = "|t24:24:xynode/icons/xynode_boss_over.dds|t|cffff00 WAR CHIEF OZOZAI |r|t24:24:xynode/icons/xynode_boss_over.dds|t\n\nThis fight is a simple one but can get messy fast if your team don't pay attention to aoe damage and how to place themselves when certain mechanics occur.\nThe boss starts with 2 guards who will assist him in the fight to start with both of which you will need to kill fast to avoid any complications. They have shield charge abilities and also a Dragonknight standard which does large aoe damage. Kill these FIRST! For the tank, try to center the boss and watch out for his heavy attacks, they are slightly delayed so block EARLY to avoid getting ping ponged around the room. DPS can block this and survive also if they gain agro. do NOT run away.\n\n|cffff00Shock Assault|r - As soon as the fight is started and the boss is ready to attack he will launch off the platform at the target of his choosing (unless taunted). Upon landing he will hit with a large shock assault attack which hits the initial point and a small aoe radius around it. So when the boss jumps in, have your dps and healers spread out to avoid this impact.\n\n|cffff00Daedric Blast|r - Occasionally Ozozai will cast a red beam on a member of your group and this will start a spreading aoe effect under the player's feet. Once this reaches its peak it will explode. You have two choices, move away from your group and let it explode(while holding block) OR have the group move away from you. Which ever is easiest. Be sure to be blocking or shielding however. Anyone else caught in the explosion will of course take damage.\n\n|cffff00Staggering Roar|r - When he is low health (enraged mechanic) he will occasionally shout! Doing moderate physical damage in aoe. This can be avoided if you are a ranged dps or healer but if you are melee be sure to block or move away when this happens. This continues until he or you are dead.\n\n\n"
				},
			[3] =
				{
					name = "BROODBIRTHER",
					mechanic = "|t24:24:xynode/icons/xynode_boss_over.dds|t|cffff00 BROODBIRTHER |r|t24:24:xynode/icons/xynode_boss_over.dds|t\n\nThis boss has two minions who should be taunted and stacked on top of the boss by the tank. It is important that the tank turns the boss away from the group to avoid any frontal aoe effects hitting them. All dps and healers should be BEHIND the boss. The 2 minions should die quite fast to aoe but be sure to kill them fast, the tank has a lot of blocking to do in this fight and it is safe to not over burn his/her resources.\n\n|cffff00Pull/Chain|r - Randomly through out the fight the boss will turn on one of the group members and PULL them in to his feet, do not panic, once you are pulled simply move away back to where you were and have your tank keep agro on him. Note if you go TOO far away from the boss he will just keep pulling you in so stay fairly close.\n\n|cffff00Shocking Rake|r - This is a frontal cone shaped aoe effect aimed at whoever has the agro (hopefully the tank). It is a rapid series of hits which cause lightning damage and hit pretty hard if not blocking. Be sure that your tank is blocking this mechanic and standing STILL, do not run around because the cone will follow your position and hit the group. TIP: Don't spin the boss!\n\nThe remainder of the attacks are mostly light attacks which don't hit so hard, even a dps can take it, but you will occasionally get a heavy attack aimed at you. Be sure to block this. It isn't a one shot as such  but can  be problematic if you keep getting thrown about.\n\n\n"
				},
			[4] =
				{
					name = "CLATTERCLAW",
					mechanic = "|t24:24:xynode/icons/xynode_boss_over.dds|t|cffff00 CLATTERCLAW |r|t24:24:xynode/icons/xynode_boss_over.dds|t\n\nThis boss is VERY straight forward, have your tank keep him as still as possible while your dps applies damage. Generally as with most bosses it makes sense to get your dps and healers to stand behind the boss if possible (or to the side) so that they are not in his face.\n\n|cffff00Mudcrab Swarm|r - This boss has some very basic mechanics in that he pretty much only ever really heavy attacks BUT if your group is lacking damage or specifically aoe damage his swarm mechanic can be pretty tough.\nEvery 10seconds or so (sometimes less) he will spawn around 8-10 mudcrabs. These are very small, similar to the swarms you encountered before the boss fight but of course you have those AND the boss to deal with. The simple solution to this is to have your tank put down some form of crowd control (ie talons if on a Dragonknight, grip if you are a warden etc) and then burn them down with aoe damage while focusing the boss.\nNOTE: DO NOT run away if mudcrabs are hitting you, just stay in the heals and keep doing what you are doing, running means you will make a mess of the fight and all control goes out of the window!\n\n\n"
				},
			[5] =
				{
					name = "KRA'GH THE DREUGH KING",
					mechanic = "|t24:24:xynode/icons/xynode_boss_over.dds|t|cffff00 KRA'GH THE DREUGH KING |r|t24:24:xynode/icons/xynode_boss_over.dds|t\n\nThe final boss in Fungal Grotto I has some simple yet devastating mechanics, one above all which to a dps or healer is a guaranteed ONE SHOT on hard mode. Your group need to coordinate and your tank needs to be as still as possible.\n\n|cffff00Lunging strike|r - This is pretty much a heavy attack but it will knock the tank for miles if not blocked and if it hits a dps who does not block it WILL kill them.\n\n|cffff00Storm Flurry|r - This is a rapid striking lightning attack aimed at the tank (or whoever has agro) A very strong tank could take the full flurry but i would highly recommend blocking it, and if you are a dps definitely make sure you block it.\n\n|cffff00Horde of Mudcrabs|r - Pretty much what it says on the tin. Just like Clatterclaw he will dig into the ground and spawn mudcrabs to attack you. This is not so stressful as it is only about 3-4 crabs but they must die fast. Aoe damage on the floor under the boss while the tank pins them in place should be more than enough.\n\n|cffff00Lightning Field|r - This is the most obvious and deadly mechanic in the fight and even the most experienced players get cocky with it and die. Kra'gh will channel a spreading LARGE aoe effect on the ground and then once it reaches its peak it will explode! unless you are a tank, ANYONE caught in this, is dead. Do NOT stand in stupid! Be sure to get out as fast as possible, let it explode, then get back in again. The tank has two choices...Block it and get knocked down, or do the same as the rest of the group. Get out and get back in again.\n\nAbove all this is quite a mobile fight due to some of the mechanics so be sure to get back into position and hold that boss still as much as you can, don't let him run wild."
				}
		}
	}
}
